parser: babel-eslint
rules:
  # react/prop-types: 1
  arrow-parens: [1, as-needed]
  block-spacing: 1
  brace-style: [1, 1tbs, allowSingleLine: true]
  curly: [2, multi-line]
  eqeqeq: 1
  indent: [2, 2]
  jsx-quotes: 1
  keyword-spacing: 1
  linebreak-style: [2, unix]
  no-multiple-empty-lines: [2, max: 1]
  no-unused-vars: 1
  object-curly-spacing: [1, always]
  quotes: [2, double]
  react/jsx-boolean-value: 1
  react/jsx-closing-bracket-location: 1
  react/jsx-curly-spacing: 1
  react/jsx-equals-spacing: 1
  react/jsx-indent-props: 1
  react/jsx-key: 1
  react/jsx-no-duplicate-props: 1
  react/jsx-no-undef: 1
  react/jsx-pascal-case: 1
  react/jsx-sort-props: [1, callbacksLast: true]
  react/jsx-space-before-closing: [1, always]
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/no-danger: 1
  react/no-did-mount-set-state: 1
  react/no-did-update-set-state: 1
  react/no-multi-comp: 1
  react/no-unknown-property: 1
  react/react-in-jsx-scope: 1
  react/require-extension: 1
  react/self-closing-comp: 1
  react/sort-comp: 1
  react/wrap-multilines: 1
  semi: [2, always]
  space-before-blocks: [1, always]
  space-in-parens: 1
  strict: 0
env:
  es6: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  modules: true
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
globals:
  API_ENDPOINT: true
